# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    tfile=$(mktemp XXXXXXXXX)
    replstr="refs/heads/"
    subststr=""
    branch=${BUILD_SOURCEBRANCH/refs\/heads\//$subststr/}
    echo $branch
    accessToken = ${BUILD_ACCESSTOKEN}
    echo $accessToken
    git remote add $tfile https://$accessToken:JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo
    git remote -v
    git checkout -b $BUILD_SOURCEBRANCHNAME
    git push -u $tfile $BUILD_SOURCEBRANCHNAME 
  displayName: 'update Azure repo'
