# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    tfile=$(mktemp XXXXXXXXX)
    replstr="refs/heads/"
    subststr=""
    branch=${$BUILD_SOURCEBRANCH/$replstr/$subststr/}
    echo $branch
    git remote add $tfile https://cxcirkre2vscnimvu5tkw7yvsckonpdtojjjagl7ifc7l5bcdhta:JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo
    git remote -v
    #git checkout -b $BUILD_SOURCEBRANCHNAME
    #git -c http.extraheader="AUTHORIZATION: bearer ***" push -u $tfile $BUILD_SOURCEBRANCHNAME 

#$branch="$(Build.SourceBranch)".replace("refs/heads/","")
#git remote add vsts https://Personal%20Access%20Token:PAT@account.visualstudio.com/project/_git/repo
#git checkout $branch
#git push vsts $branch -f
    
    
  displayName: 'Run a multi-line script'
