# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo "##vso[task.setvariable variable=accessToken;issecret=true]this is the access token value"
  name: setvarStep
- script: echo $(setvarStep.accessToken)
  name: echovar

- script: |
    export
    tfile=$(mktemp XXXXXXXXX)
    replstr="refs/heads/"
    subststr=""
    branch=${BUILD_SOURCEBRANCH/refs\/heads\//$subststr/}
    echo $branch
    echo $MYSECRET
    git remote add $tfile https://$MYSECRET:JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo
    git remote -v
    git checkout -b $BUILD_SOURCEBRANCHNAME
    git push -u $tfile $BUILD_SOURCEBRANCHNAME 
  displayName: 'update Azure repo'
 
