# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    git config gc.auto 0
    git config --get-all http.https://JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo.extraheader
    git remote add vsts https://JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo
    git config --get-all http.proxy
    git checkout -b $BUILD_SOURCEBRANCHNAME
    git -c http.extraheader="AUTHORIZATION: bearer ***" push -u vsts $BUILD_SOURCEBRANCHNAME 
  displayName: 'Run a multi-line script'
