# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    # get the personal access token and save to variable
    echo "##vso[task.setvariable variable=accessToken;issecret=true]this is the access token value"
    
    # create a temp file to get a unique name
    tfile=$(mktemp XXXXXXXXX)
    
    # add new remote using the unique name
    git remote add $tfile https://$(accessToken):JWilson0130@dev.azure.com/JWilson0130/Rails%20demo/_git/Rails%20demo
    
    # switch to current branch
    git checkout -b $BUILD_SOURCEBRANCHNAME
    
    # push branch
    git push -u $tfile $BUILD_SOURCEBRANCHNAME 
    
  displayName: 'update Azure repo with Github change'
